// initData
export const INIT_APP_DATA = 'INIT_APP_DATA'
export const SET_RECOMMEND_LIST_DATA = 'SET_RECOMMEND_LIST_DATA'

// common
export const DRAWER_LOCK_MODE = 'DRAWER_LOCK_MODE'
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS'
export const SET_MAINVIEW_STATUS = 'SET_MAINVIEW_STATUS'
export const PLAYLISTMODAL_WATCHER = 'PLAYLISTMODAL_WATCHER'
export const PLAYLISTMODAL_STATUS  = 'PLAYLISTMODAL_STATUS'
export const OPEN_PLAYLISTMODAL = 'OPEN_PLAYLISTMODAL'
export const CLOSE_PLAYLISTMODAL = 'CLOSE_PLAYLISTMODAL'

// player
export const PLAYER_BOX_WATCHER = 'PLAYER_BOX_WATCHER'
export const PLAYER_BOX_STATUS = 'PLAYER_BOX_STATUS'
export const PLAYER_BOX_OPEN = 'PLAYER_BOX_OPEN'
export const PLAYER_BOX_CLOSE = 'PLAYER_BOX_CLOSE'

export const AUDIO_WATCHER = 'AUDIO_WATCHER'
export const PLAYER_STATUS = 'PLAYER_STATUS'
export const IS_SLIDING = 'IS_SLIDING'
export const SET_CURRENTTIME = 'SET_CURRENTTIME'
export const SET_DURATION = 'SET_DURATION'
export const SLIDER_WATCHER = 'SLIDER_WATCHER'
export const SET_SLIDER_VALUE = 'SET_SLIDER_VALUE'
export const SET_SLIDER_VALUE_END = 'SET_SLIDER_VALUE_END'

// sheet
export const GET_USER_ALBUMLIST = 'GET_USER_ALBUMLIST'
export const SET_USER_ALBUMLIST = 'SET_USER_ALBUMLIST'
export const GET_ALBUM_INFO = 'GET_ALBUM_INFO'
export const SET_ALBUM_INFO = 'SET_ALBUM_INFO'

// plalist 
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_MODAL_PLAYLIST = 'SET_MODAL_PLAYLIST'
export const SET_PLAYINGINDEX = 'SET_PLAYINGINDEX'
export const PUT_ALBUM_TO_PLAYLIST = 'PUT_ALBUM_TO_PLAYLIST'
export const REMOVE_TRACK = 'REMOVE_TRACK'
export const ADD_TRACK = 'ADD_TRACK'
export const SHUFFLE_PLAYLIST = 'SHUFFLE_PLAYLIST'

// user
export const LOGIN_START = 'LOGIN_START'
export const LOGOUT_START = 'LOGOUT_START'
export const SET_PROFILE = 'SET_PROFILE'
export const CHECK_LOGIN_STATUS = 'CHECK_LOGIN_STATUS'