// common
export const DRAWER_LOCK_MODE = 'DRAWER_LOCK_MODE'

// player
export const PLAYER_BOX_WATCHER = 'PLAYER_BOX_WATCHER'
export const PLAYER_BOX_STATUS = 'PLAYER_BOX_STATUS'
export const PLAYER_BOX_OPEN = 'PLAYER_BOX_OPEN'
export const PLAYER_BOX_CLOSE = 'PLAYER_BOX_CLOSE'

export const AUDIO_WATCHER = 'AUDIO_WATCHER'
export const PLAYER_STATUS = 'PLAYER_STATUS'
export const IS_SLIDING = 'IS_SLIDING'
export const SET_CURRENTTIME = 'SET_CURRENTTIME'
export const SET_DURATION = 'SET_DURATION'
export const SLIDER_WATCHER = 'SLIDER_WATCHER'
export const SET_SLIDER_VALUE = 'SET_SLIDER_VALUE'
export const SET_SLIDER_VALUE_END = 'SET_SLIDER_VALUE_END'
